# This is a basic workflow to help you get started with Actions

name: linux1
on:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }} #以 workflow 名称作为唯一分组键，相同 workflow 名称的实例将归为一组。
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo "build ssh start"
          sudo apt update && sudo apt install openssh-server
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}
          mkdir ~/.ssh
          touch ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          cat ./id_rsa.pub >> ~/.ssh/authorized_keys
          sudo systemctl restart ssh.service
          echo "build ssh end"

      - name: cloudflare start
        run: |
          echo "cloudflare start"
          echo GITHUB_WORKSPACE
          cd ${GITHUB_WORKSPACE}
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          cloudflaredCode=$(openssl enc -d -aes-256-cbc -pbkdf2 -in cloudflared/linux1.enc.txt -k ${{ secrets.WIN_CODE }})
          sudo cloudflared service install $cloudflaredCode
          echo "cloudflare end"
          
      - name: end 
        run: |
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}
          chmod +x end.sh
          ./end.sh

          
