# This is a basic workflow to help you get started with Actions

name: linux
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo "build ssh start"
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}
          mkdir ~/.ssh
          touch ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          cat ./id_rsa.pub >> ~/.ssh/authorized_keys
          sudo systemctl restart sshd.service
          echo "build ssh end"

      - name: cloudflare start
        run: |
          echo "cloudflare start"
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          sudo cloudflared service install ${{ secrets.CLOUD_GITHUB }}
          echo "cloudflare end"

      - name: code-server
        run: |
          echo GITHUB_WORKSPACE
          cd ${GITHUB_WORKSPACE}
          pwd
          ls -al
          sed -i -r "s/codeSecret/${{ secrets.CODE }}/g" ./config.yaml
          echo "code-server start"
          curl -fsSL https://code-server.dev/install.sh | sudo sh
          mkdir -p ~/.config/code-server
          touch ~/.config/code-server/config.yaml
          cat ./config.yaml >>~/.config/code-server/config.yaml
          cat ~/.config/code-server/config.yaml
          sudo systemctl enable --now code-server@$USER
          sudo systemctl start code-server@$USER
          sudo systemctl status code-server@$USER
          echo "code-server end"
          
      - name: end 
        run: |
          echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}
          chmod +x end.sh
          ./end.sh

          
